apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: read-verticle
    visualize: "true"
  name: read-verticle-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: read-verticle
        env: prod
        app: vertx-cluster-01
        visualize: "true"
    spec:
      containers:
      - image: gcr.io/kubernetestests-147607/vxms-read:v13
        name: read-verticle
        ports:
        - name: read-verticle
          containerPort: 8282
          hostPort: 8282
