kind: Service
apiVersion: v1
metadata:
  labels:
    expose: true
    name: ${project.artifactId}
    version: ${project.parent.version}
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8181